name: tests

on:
  push:
    branches: [ "mysql" ]
  pull_request:
    branches: [ "mysql" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - run: env
    - run: php -r 'var_dump(gethostname());'
    - run: php -r 'var_dump(__LINE__);'
    - run: php -r 'var_dump(__FILE__);'
    - run: php -r 'var_dump(__DIR__);'
    - run: php -r 'var_dump(__FUNCTION__);'
    - run: php -r 'var_dump(__CLASS__);'
    - run: php -r 'var_dump(__TRAIT__);'
    - run: php -r 'var_dump(__METHOD__);'
    - run: php -r 'var_dump(__NAMESPACE__);'
    - run: php -r 'var_dump(ClassName::class);'
    - run: php -r 'var_dump(PHP_VERSION);'
    - run: php -r 'var_dump(PHP_MAJOR_VERSION);'
    - run: php -r 'var_dump(PHP_MINOR_VERSION);'
    - run: php -r 'var_dump(PHP_RELEASE_VERSION);'
    - run: php -r 'var_dump(PHP_VERSION_ID);'
    - run: php -r 'var_dump(PHP_EXTRA_VERSION);'
    - run: php -r 'var_dump(PHP_ZTS);'
    - run: php -r 'var_dump(PHP_DEBUG);'
    - run: php -r 'var_dump(PHP_MAXPATHLEN);'
    - run: php -r 'var_dump(PHP_OS);'
    - run: php -r 'var_dump(PHP_OS_FAMILY);'
    - run: php -r 'var_dump(PHP_SAPI);'
    - run: php -r 'var_dump(PHP_EOL);'
    - run: php -r 'var_dump(PHP_INT_MAX);'
    - run: php -r 'var_dump(PHP_INT_MIN);'
    - run: php -r 'var_dump(PHP_INT_SIZE);'
    - run: php -r 'var_dump(PHP_FLOAT_DIG);'
    - run: php -r 'var_dump(PHP_FLOAT_EPSILON);'
    - run: php -r 'var_dump(PHP_FLOAT_MIN);'
    - run: php -r 'var_dump(PHP_FLOAT_MAX);'
    - run: php -r 'var_dump(DEFAULT_INCLUDE_PATH);'
    - run: php -r 'var_dump(PEAR_INSTALL_DIR);'
    - run: php -r 'var_dump(PEAR_EXTENSION_DIR);'
    - run: php -r 'var_dump(PHP_EXTENSION_DIR);'
    - run: php -r 'var_dump(PHP_PREFIX);'
    - run: php -r 'var_dump(PHP_BINDIR);'
    - run: php -r 'var_dump(PHP_BINARY);'
    - run: php -r 'var_dump(PHP_MANDIR);'
    - run: php -r 'var_dump(PHP_LIBDIR);'
    - run: php -r 'var_dump(PHP_DATADIR);'
    - run: php -r 'var_dump(PHP_SYSCONFDIR);'
    - run: php -r 'var_dump(PHP_LOCALSTATEDIR);'
    - run: php -r 'var_dump(PHP_CONFIG_FILE_PATH);'
    - run: php -r 'var_dump(PHP_CONFIG_FILE_SCAN_DIR);'
    - run: php -r 'var_dump(PHP_SHLIB_SUFFIX);'
    - run: php -r 'var_dump(PHP_FD_SETSIZE);'
    - run: php -r 'var_dump(E_ERROR);'
    - run: php -r 'var_dump(E_WARNING);'
    - run: php -r 'var_dump(E_PARSE);'
    - run: php -r 'var_dump(E_NOTICE);'
    - run: php -r 'var_dump(E_CORE_ERROR);'
    - run: php -r 'var_dump(E_CORE_WARNING);'
    - run: php -r 'var_dump(E_COMPILE_ERROR);'
    - run: php -r 'var_dump(E_COMPILE_WARNING);'
    - run: php -r 'var_dump(E_USER_ERROR);'
    - run: php -r 'var_dump(E_USER_WARNING);'
    - run: php -r 'var_dump(E_USER_NOTICE);'
    - run: php -r 'var_dump(E_RECOVERABLE_ERROR);'
    - run: php -r 'var_dump(E_DEPRECATED);'
    - run: php -r 'var_dump(E_USER_DEPRECATED);'
    - run: php -r 'var_dump(E_ALL);'
    - run: php -r 'var_dump(E_STRICT);'
    - run: php -r 'var_dump(__COMPILER_HALT_OFFSET__);'
    - run: php -r 'var_dump(true);'
    - run: php -r 'var_dump(false);'
    - run: php -r 'var_dump(null);'
    - run: php -r 'var_dump(PHP_WINDOWS_EVENT_CTRL_C);'
    - run: php -r 'var_dump(PHP_WINDOWS_EVENT_CTRL_BREAK);'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Compress
      run: tar cf /tmp/laravel.tar.gz .
    - uses: actions/upload-artifact@v3
      with:
        path: /tmp/laravel.tar.gz
